baseurl: 'nurtureblossombc.github.io/'
permalink: pretty
title: 'Nurture and Blossom Behaviour Consulting'
email: 'webmaster@arcana.com.au'
description: 'Board Certified Behaviour Analyst providing individualised care for children with developmental needs. Specialising in Applied Behaviour Analysis to nurture skills and cultivate futures.'

homepage:
  show_call_box: true

footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Nurture and Blossom Behaviour Consulting"
  meta_og_type: "website"
  meta_og_url: "https://nurtureblossombc.com.au"
  meta_og_image: "https://nurtureblossombc.com.au/images/social.png"
  meta_og_description: "Board Certified Behaviour Analyst providing individualised care for children with developmental needs. Specialising in Applied Behaviour Analysis to nurture skills and cultivate futures."
  google_analytics_id: ""

logo:
  mobile: "images/logo/logo.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "50px"

home: 
  limit_services: 3

collections:
  services:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "values"
    values:
      layout: "product"
  - scope:
      path: ""
      type: "about"
    values:
      layout: "team"

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

url: "https://nurtureblossombc.com.au"

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

