baseurl: ''
permalink: pretty
title: 'Jeff Tate Consulting'
email: 'webmaster@arcana.com.au'
description: 'Jeff is a specialist in policy and strategy development, review and implementation; organisational alignment; partnering and relationships; governance; problem solving; leadership mentoring and coaching; and facilitation and negotiation.'

homepage:
  show_call_box: true

footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Jeff Tate Consulting"
  meta_og_type: "website"
  meta_og_url: "https://tateconsulting.com.au"
  meta_og_image: "https://tateconsulting.com.au/images/jeff_tate.jpg"
  meta_og_description: "Jeff is a specialist in policy and strategy development, review and implementation; organisational alignment; partnering and relationships; governance; problem solving; leadership mentoring and coaching; and facilitation and negotiation."
  google_analytics_id: ""

logo:
  mobile: "images/logo/logo.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "50px"

home: 
  limit_services: 3

collections:
  services:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "values"
    values:
      layout: "product"
    values:
      layout: "team"

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

url: "https://jessearcana.github.io/tateconsulting.github.io"

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

